# Code Generated by LambdaGrader
try:
    _did_pass = True
    _message = ''
# TEST_CASE_REPLACE_HERE
except BaseException as ex:
    _did_pass = False
    _message = type(ex).__name__ + ': ' + str(ex)
    raise
finally:
    _record_test_case(_test_case, _did_pass, _points, _message)